// Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// WARNING: THIS FILE WAS AUTOMATICALLY GENERATED.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuda

/*
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
#include "cuda.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// CUresult as declared in cuda/cuda.h
type CUresult int32

// CUresult enumeration from cuda/cuda.h
const (
	SUCCESS                              CUresult = iota
	ERROR_INVALID_VALUE                  CUresult = 1
	ERROR_OUT_OF_MEMORY                  CUresult = 2
	ERROR_NOT_INITIALIZED                CUresult = 3
	ERROR_DEINITIALIZED                  CUresult = 4
	ERROR_PROFILER_DISABLED              CUresult = 5
	ERROR_PROFILER_NOT_INITIALIZED       CUresult = 6
	ERROR_PROFILER_ALREADY_STARTED       CUresult = 7
	ERROR_PROFILER_ALREADY_STOPPED       CUresult = 8
	ERROR_NO_DEVICE                      CUresult = 100
	ERROR_INVALID_DEVICE                 CUresult = 101
	ERROR_INVALID_IMAGE                  CUresult = 200
	ERROR_INVALID_CONTEXT                CUresult = 201
	ERROR_CONTEXT_ALREADY_CURRENT        CUresult = 202
	ERROR_MAP_FAILED                     CUresult = 205
	ERROR_UNMAP_FAILED                   CUresult = 206
	ERROR_ARRAY_IS_MAPPED                CUresult = 207
	ERROR_ALREADY_MAPPED                 CUresult = 208
	ERROR_NO_BINARY_FOR_GPU              CUresult = 209
	ERROR_ALREADY_ACQUIRED               CUresult = 210
	ERROR_NOT_MAPPED                     CUresult = 211
	ERROR_NOT_MAPPED_AS_ARRAY            CUresult = 212
	ERROR_NOT_MAPPED_AS_POINTER          CUresult = 213
	ERROR_ECC_UNCORRECTABLE              CUresult = 214
	ERROR_UNSUPPORTED_LIMIT              CUresult = 215
	ERROR_CONTEXT_ALREADY_IN_USE         CUresult = 216
	ERROR_PEER_ACCESS_UNSUPPORTED        CUresult = 217
	ERROR_INVALID_PTX                    CUresult = 218
	ERROR_INVALID_GRAPHICS_CONTEXT       CUresult = 219
	ERROR_NVLINK_UNCORRECTABLE           CUresult = 220
	ERROR_JIT_COMPILER_NOT_FOUND         CUresult = 221
	ERROR_INVALID_SOURCE                 CUresult = 300
	ERROR_FILE_NOT_FOUND                 CUresult = 301
	ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND CUresult = 302
	ERROR_SHARED_OBJECT_INIT_FAILED      CUresult = 303
	ERROR_OPERATING_SYSTEM               CUresult = 304
	ERROR_INVALID_HANDLE                 CUresult = 400
	ERROR_NOT_FOUND                      CUresult = 500
	ERROR_NOT_READY                      CUresult = 600
	ERROR_ILLEGAL_ADDRESS                CUresult = 700
	ERROR_LAUNCH_OUT_OF_RESOURCES        CUresult = 701
	ERROR_LAUNCH_TIMEOUT                 CUresult = 702
	ERROR_LAUNCH_INCOMPATIBLE_TEXTURING  CUresult = 703
	ERROR_PEER_ACCESS_ALREADY_ENABLED    CUresult = 704
	ERROR_PEER_ACCESS_NOT_ENABLED        CUresult = 705
	ERROR_PRIMARY_CONTEXT_ACTIVE         CUresult = 708
	ERROR_CONTEXT_IS_DESTROYED           CUresult = 709
	ERROR_ASSERT                         CUresult = 710
	ERROR_TOO_MANY_PEERS                 CUresult = 711
	ERROR_HOST_MEMORY_ALREADY_REGISTERED CUresult = 712
	ERROR_HOST_MEMORY_NOT_REGISTERED     CUresult = 713
	ERROR_HARDWARE_STACK_ERROR           CUresult = 714
	ERROR_ILLEGAL_INSTRUCTION            CUresult = 715
	ERROR_MISALIGNED_ADDRESS             CUresult = 716
	ERROR_INVALID_ADDRESS_SPACE          CUresult = 717
	ERROR_INVALID_PC                     CUresult = 718
	ERROR_LAUNCH_FAILED                  CUresult = 719
	ERROR_COOPERATIVE_LAUNCH_TOO_LARGE   CUresult = 720
	ERROR_NOT_PERMITTED                  CUresult = 800
	ERROR_NOT_SUPPORTED                  CUresult = 801
	ERROR_UNKNOWN                        CUresult = 999
)
