// Copyright (c) 2022, NVIDIA CORPORATION. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// WARNING: THIS FILE WAS AUTOMATICALLY GENERATED.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cuda

/*
#cgo LDFLAGS: -Wl,--unresolved-symbols=ignore-in-object-files
#include "cuda.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// cuDriverGetVersion function as declared in cuda/cuda.h
func cuDriverGetVersion(DriverVersion *int32) CUresult {
	cDriverVersion, _ := (*C.int)(unsafe.Pointer(DriverVersion)), cgoAllocsUnknown
	__ret := C.cuDriverGetVersion(cDriverVersion)
	__v := (CUresult)(__ret)
	return __v
}
